import type { FunctionBlockDef } from '../types/function-block';

export const MATH_BLOCKS: FunctionBlockDef[] = [
  {
    type: 'math.add',
    category: 'math',
    name: 'Add',
    symbol: '+',
    description: 'Add two inputs',
    inputs: [
      { id: 'in1', name: 'A', dataType: 'number' },
      { id: 'in2', name: 'B', dataType: 'number' },
    ],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 100, height: 70 },
    execute: (inputs) => ({
      outputs: { out: (inputs.in1 ?? 0) + (inputs.in2 ?? 0) },
      state: {},
    }),
    codeGen: {
      c: { expression: '({in1} + {in2})' },
      scl: { expression: '({in1} + {in2})' },
    },
  },
  {
    type: 'math.sub',
    category: 'math',
    name: 'Subtract',
    symbol: '\u2212',
    description: 'Subtract B from A',
    inputs: [
      { id: 'in1', name: 'A', dataType: 'number' },
      { id: 'in2', name: 'B', dataType: 'number' },
    ],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 100, height: 70 },
    execute: (inputs) => ({
      outputs: { out: (inputs.in1 ?? 0) - (inputs.in2 ?? 0) },
      state: {},
    }),
    codeGen: {
      c: { expression: '({in1} - {in2})' },
      scl: { expression: '({in1} - {in2})' },
    },
  },
  {
    type: 'math.mul',
    category: 'math',
    name: 'Multiply',
    symbol: '\u00d7',
    description: 'Multiply two inputs',
    inputs: [
      { id: 'in1', name: 'A', dataType: 'number' },
      { id: 'in2', name: 'B', dataType: 'number' },
    ],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 100, height: 70 },
    execute: (inputs) => ({
      outputs: { out: (inputs.in1 ?? 0) * (inputs.in2 ?? 0) },
      state: {},
    }),
    codeGen: {
      c: { expression: '({in1} * {in2})' },
      scl: { expression: '({in1} * {in2})' },
    },
  },
  {
    type: 'math.div',
    category: 'math',
    name: 'Divide',
    symbol: '\u00f7',
    description: 'Divide A by B',
    inputs: [
      { id: 'in1', name: 'A', dataType: 'number' },
      { id: 'in2', name: 'B', dataType: 'number' },
    ],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 100, height: 70 },
    execute: (inputs) => ({
      outputs: { out: (inputs.in2 ?? 0) !== 0 ? (inputs.in1 ?? 0) / (inputs.in2 ?? 1) : 0 },
      state: {},
    }),
    codeGen: {
      c: { expression: '({in1} / {in2})' },
      scl: { expression: '({in1} / {in2})' },
    },
  },
  {
    type: 'math.gain',
    category: 'math',
    name: 'Gain',
    symbol: 'K',
    description: 'Multiply input by constant gain',
    inputs: [{ id: 'in', name: 'In', dataType: 'number' }],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [
      { id: 'K', name: 'Gain (K)', type: 'number', defaultValue: 1, step: 0.1 },
    ],
    defaultSize: { width: 100, height: 60 },
    execute: (inputs, params) => ({
      outputs: { out: (inputs.in ?? 0) * (Number(params.K) || 1) },
      state: {},
    }),
    codeGen: {
      c: { expression: '({in} * {K})' },
      scl: { expression: '({in} * {K})' },
    },
  },
  {
    type: 'math.abs',
    category: 'math',
    name: 'Abs',
    symbol: '|u|',
    description: 'Absolute value',
    inputs: [{ id: 'in', name: 'In', dataType: 'number' }],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 90, height: 60 },
    execute: (inputs) => ({
      outputs: { out: Math.abs(inputs.in ?? 0) },
      state: {},
    }),
    codeGen: {
      c: { expression: 'abs({in})', includes: ['<stdlib.h>'] },
      scl: { expression: 'ABS({in})' },
    },
  },
  {
    type: 'math.neg',
    category: 'math',
    name: 'Negate',
    symbol: '-u',
    description: 'Negate input',
    inputs: [{ id: 'in', name: 'In', dataType: 'number' }],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 90, height: 60 },
    execute: (inputs) => ({
      outputs: { out: -(inputs.in ?? 0) },
      state: {},
    }),
    codeGen: {
      c: { expression: '(-{in})' },
      scl: { expression: '(-{in})' },
    },
  },
  {
    type: 'math.sqrt',
    category: 'math',
    name: 'Sqrt',
    symbol: '\u221a',
    description: 'Square root',
    inputs: [{ id: 'in', name: 'In', dataType: 'number' }],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 90, height: 60 },
    execute: (inputs) => ({
      outputs: { out: Math.sqrt(Math.max(0, inputs.in ?? 0)) },
      state: {},
    }),
    codeGen: {
      c: { expression: 'sqrt({in})', includes: ['<math.h>'] },
      scl: { expression: 'SQRT({in})' },
    },
  },
  {
    type: 'math.square',
    category: 'math',
    name: 'Square',
    symbol: 'u\u00b2',
    description: 'Square of input',
    inputs: [{ id: 'in', name: 'In', dataType: 'number' }],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 90, height: 60 },
    execute: (inputs) => ({
      outputs: { out: (inputs.in ?? 0) * (inputs.in ?? 0) },
      state: {},
    }),
    codeGen: {
      c: { expression: '({in} * {in})' },
      scl: { expression: '({in} * {in})' },
    },
  },
  {
    type: 'math.min',
    category: 'math',
    name: 'Min',
    symbol: 'min',
    description: 'Minimum of two inputs',
    inputs: [
      { id: 'in1', name: 'A', dataType: 'number' },
      { id: 'in2', name: 'B', dataType: 'number' },
    ],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 100, height: 70 },
    execute: (inputs) => ({
      outputs: { out: Math.min(inputs.in1 ?? 0, inputs.in2 ?? 0) },
      state: {},
    }),
    codeGen: {
      c: { expression: '(({in1} < {in2}) ? {in1} : {in2})' },
      scl: { expression: 'MIN(IN1 := {in1}, IN2 := {in2})' },
    },
  },
  {
    type: 'math.max',
    category: 'math',
    name: 'Max',
    symbol: 'max',
    description: 'Maximum of two inputs',
    inputs: [
      { id: 'in1', name: 'A', dataType: 'number' },
      { id: 'in2', name: 'B', dataType: 'number' },
    ],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 100, height: 70 },
    execute: (inputs) => ({
      outputs: { out: Math.max(inputs.in1 ?? 0, inputs.in2 ?? 0) },
      state: {},
    }),
    codeGen: {
      c: { expression: '(({in1} > {in2}) ? {in1} : {in2})' },
      scl: { expression: 'MAX(IN1 := {in1}, IN2 := {in2})' },
    },
  },
  {
    type: 'math.limit',
    category: 'math',
    name: 'Limit',
    symbol: 'lim',
    description: 'Clamp input between lo and hi',
    inputs: [
      { id: 'in', name: 'In', dataType: 'number' },
      { id: 'lo', name: 'Lo', dataType: 'number' },
      { id: 'hi', name: 'Hi', dataType: 'number' },
    ],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 100, height: 90 },
    execute: (inputs) => ({
      outputs: {
        out: Math.max(inputs.lo ?? 0, Math.min(inputs.hi ?? 0, inputs.in ?? 0)),
      },
      state: {},
    }),
    codeGen: {
      c: { expression: '(({in} < {lo}) ? {lo} : (({in} > {hi}) ? {hi} : {in}))' },
      scl: { expression: 'LIMIT(MN := {lo}, IN := {in}, MX := {hi})' },
    },
  },
  {
    type: 'math.mod',
    category: 'math',
    name: 'Modulo',
    symbol: 'mod',
    description: 'Remainder of A / B',
    inputs: [
      { id: 'in1', name: 'A', dataType: 'number' },
      { id: 'in2', name: 'B', dataType: 'number' },
    ],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 100, height: 70 },
    execute: (inputs) => ({
      outputs: { out: (inputs.in2 ?? 0) !== 0 ? (inputs.in1 ?? 0) % (inputs.in2 ?? 1) : 0 },
      state: {},
    }),
    codeGen: {
      c: { expression: '({in1} % {in2})' },
      scl: { expression: '({in1} MOD {in2})' },
    },
  },
  {
    type: 'math.pow',
    category: 'math',
    name: 'Power',
    symbol: 'u^n',
    description: 'Base raised to exponent',
    inputs: [
      { id: 'base', name: 'Base', dataType: 'number' },
      { id: 'exp', name: 'Exp', dataType: 'number' },
    ],
    outputs: [{ id: 'out', name: 'Out', dataType: 'number' }],
    params: [],
    defaultSize: { width: 100, height: 70 },
    execute: (inputs) => ({
      outputs: { out: Math.pow(inputs.base ?? 0, inputs.exp ?? 0) },
      state: {},
    }),
    codeGen: {
      c: { expression: 'pow({base}, {exp})', includes: ['<math.h>'] },
      scl: { expression: 'EXPT(IN1 := {base}, IN2 := {exp})' },
    },
  },
];
